version: '3.7'
services:
    nginx:
        build:
            context: ./docker
            dockerfile: nginx.docker
        volumes:
            - ./:/var/www
        ports:
            - "8001:80"
        networks:
          - backend
    php-fpm:
        build:
            context: ./docker
            dockerfile: php-fpm.docker
        volumes:
            - ./:/var/www
        depends_on:
          - api-postgres
        networks:
          - backend
    php-cli:
        build:
            context: ./docker
            dockerfile: php-cli.docker
        volumes:
            - ./:/var/www
        depends_on:
          - api-postgres
        networks:
          - backend
        working_dir: /var/www
        tty: true
    api-postgres:
        image: postgres:12.2-alpine
        environment:
            DB_USERNAME: app
            DB_PASSWORD: secret
            DB_DATABASE: app
        volumes:
          - api-postgres:/var/lib/postgresql/data
        ports:
          - "54321:5432"
        networks:
          - backend
volumes:
  api-postgres:
networks:
  backend:
    driver: bridge
